### ISSUE TITLE
Adding a robots.txt file

### ISSUE THREAD

**Issue by pranavnbapat** [openagri-eu/OpenAgri-Bootstrap-Deployment#20]
We need to add robots.txt to control web crawlers and prevent unnecessary indexing. This slightly reduces the server load caused by aggressive crawlers.

For FastAPI, in main.py
```
@app.get("/robots.txt", response_class=PlainTextResponse)
def robots_txt():
    return "User-agent: *\nDisallow: /admin/\nDisallow: /private/"
```

For Django, in urls.py
```
def robots_txt(request):
    return HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")

urlpatterns = [
    path("robots.txt", robots_txt),
]
```

**Comment by fedjo** [comment]
Good point. I also found that we can block bots and crawlers in the reverse proxy side (traefik) which looks like a more clear solution as the engines/bots/crawlers do not reach the application.

Some useful links

[https://blog.containo.us/protect-your-services-when-using-traefik-with-rate-limiting/](https://plugins.traefik.io/plugins/66721f91b6203b47e20005b1/trafik-ultimate-bad-bot-blocker)
[https://plugins.traefik.io/plugins/66721f91b6203b47e20005b1/trafik-ultimate-bad-bot-blocker](https://plugins.traefik.io/plugins/66721f91b6203b47e20005b1/trafik-ultimate-bad-bot-blocker)
https://plugins.traefik.io/plugins/62947317ffc0cd18356a97cb/block-user-agent

I found and example configuration sth like

```
your-project/
├── docker-compose.yml
└── traefik/
    └── dynamic/
        └── bot-blocking.yml
```

```
# docker-compose.yml
version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Enable file provider for dynamic configuration
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    networks:
      - web

  your-app:
    image: your-app-image
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`example.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.middlewares=bot-blocker,rate-limit"
    networks:
      - web

networks:
  web:
    external: true

```

```
# /traefik/dynamic/bot-blocking.yml
http:
  middlewares:
    # Middleware to detect and block bots
    bot-blocker:
      chain:
        middlewares:
          - bot-detector
          - bot-filter

    # Detect bots based on User-Agent
    bot-detector:
      headers:
        customRequestHeaders:
          X-Is-Bot: "{{ if or (contains .Request.Headers.User-Agent \"bot\") (contains .Request.Headers.User-Agent \"crawler\") (contains .Request.Headers.User-Agent \"spider\") (contains .Request.Headers.User-Agent \"evaluation\") (contains .Request.Headers.User-Agent \"Googlebot\") (contains .Request.Headers.User-Agent \"Baiduspider\") (contains .Request.Headers.User-Agent \"Yandex\") (contains .Request.Headers.User-Agent \"Bingbot\") (contains .Request.Headers.User-Agent \"Slurp\") }}true{{ else }}false{{ end }}"

    # Filter detected bots
    bot-filter:
      plugin:
        ratelimit:
          average: 2
          burst: 5
          sourceCriterion:
            requestHeaderName: X-Is-Bot
            
    # Optional: Allow specific good bots (like Google)
    good-bots:
      ipWhiteList:
        sourceRange:
          # Google bot IP ranges (example)
          - "66.249.64.0/19"
          - "64.233.160.0/19"

    # Rate limiting for all traffic
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
```
